export const NOTIFICATIONS = [
	{
		id: 1,
		subject: "New user registered",
		body: "John Doe has registered",
		type: "info",
		createdAt: "2021-08-01T12:00:00.000Z",
		acknowledgedAt: null,
	},
	{
		id: 2,
		subject: "New user registered",
		body: "John Doe has registered",
		type: "warning",
		createdAt: "2021-08-01T12:00:00.000Z",
		acknowledgedAt: null,
	},
	{
		id: 3,
		subject: "New user registered",
		body: "John Doe has registered",
		type: "error",
		createdAt: "2021-08-01T12:00:00.000Z",
		acknowledgedAt: null,
	},
	{
		id: 4,
		subject: "Upload successful",
		body: "File uploaded successfully. Click to view. Other stuff goes here. Just testing to make the text really really long.",
		type: "info",
		createdAt: "2021-08-01T12:00:00.000Z",
		acknowledgedAt: null,
	},
	{
		id: 5,
		subject: "Upload successful",

		body: "File uploaded successfully. Click to view. Other stuff goes here. Just testing to make the text really really long.",
		type: "warning",
		createdAt: "2021-08-01T12:00:00.000Z",
		acknowledgedAt: null,
	},
	{
		id: 6,
		subject: "Upload successful",
		body: "File uploaded successfully. Click to view. Other stuff goes here. Just testing to make the text really really long.",

		type: "error",
		createdAt: "2021-08-01T12:00:00.000Z",
		acknowledgedAt: null,
	},
	{
		id: 7,
		subject: "Upload successful",
		body: "File uploaded successfully. Click to view. Other stuff goes here. Just testing to make the text really really long.",
		type: "info",
		createdAt: "2021-08-01T12:00:00.000Z",
		acknowledgedAt: null,
	},
];
