# Name of workflow as seen in Github actions tab
name: Deploy
# Run workflow only on push to dev or main branches
on:
    push:
        branches:
            - dev
            - main

jobs:
    #  Prebuild
    prebuild:
        name: prebuild
        runs-on: ubuntu-latest

        # Configure github actions build environment
        steps:
            # Determine environment name by branch name (banch:dev=dev or branch:main=prod)
            - name: get_env_name
              id: get_env_name
              run: |
                  echo "Running on branch ${{ github.ref }}"
                  if [ "${{ github.ref }}" = "refs/heads/main" ]; then
                      echo "::set-output name=env_name::prod"
                  elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
                      echo "::set-output name=env_name::dev"
                    fi
            - name: get_env_url
              id: get_env_url
              run: |
                  if [ "${{ steps.get_env_name.outputs.env_name }}" = "prod" ]; then
                      echo "::set-output name=env_url::https://api.fanheat.com"
                  elif [ "${{ steps.get_env_name.outputs.env_name }}" = "dev" ]; then
                      echo "::set-output name=env_url::https://api.dev.fanheat.com"
                    fi

            # Generate UUID for Elastic Beanstalk version label
            - name: Get uuid
              id: uuid
              run: |
                  echo "::set-output name=uuid::$(uuidgen)"

        outputs:
            env_name: ${{ steps.get_env_name.outputs.env_name }}
            env_url: ${{ steps.get_env_url.outputs.env_url }}
            uuid: ${{ steps.uuid.outputs.uuid }}

    # Deploy
    deploy:
        needs: prebuild
        name: deploy
        runs-on: ubuntu-latest
        strategy:
            # Ensure Node.js version is 16.x - required to run node crypto functions (they become deprecated in 17.x)
            matrix:
                node-version: [16.x]
        environment: ${{ needs.prebuild.outputs.env_name }}

        steps:
            # Initialize Deployment (required for deployment status updates such as Jira integration)
            - uses: actions/checkout@v1
            - uses: chrnorm/deployment-action@v2
              name: Initialize Deployment
              id: deployment
              with:
                  token: "${{ github.token }}"
                  environment-url: ${{ needs.prebuild.outputs.env_url }}
                  environment: ${{ needs.prebuild.outputs.env_name }}

            # Use Node.js 16.x from matrix.node-version
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            # Configure AWS credentials (requires access to Secrets Manager and Elastic Beanstalk)
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            # Get Environment Variables From AWS Secrets Manager
            - name: Get Environment Variables From AWS Secrets Manager
              run: |
                  aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRET_NAME }} --query SecretString --output text > .env

            # Install Dependencies
            - name: Install Dependencies
              run: |
                  npm install

            # Build Static Files
            - name: Build Static Files
              continue-on-error: true
              run: |
                  npm run build

            # Append Service Worker (Elastic Beanstalk won't run prestart script correctly so this must be done here)
            - name: Append Service Worker
              run: |
                  npm run sw-append:messaging

            # Generate Git Archive
            - name: Generate Git Archive
              run: git archive --format=zip --output=deploy.zip HEAD
            # Include Build Folder in Archive
            - name: Include Build Folder in Archive
              run: zip -r deploy.zip build

            # Deploy to AWS Elastic Beanstalk
            - name: Deploy to AWS Elastic Beanstalk
              uses: einaregilsson/beanstalk-deploy@v21
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
                  environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
                  version_label: ${{ needs.prebuild.outputs.uuid }}
                  region: ${{ secrets.AWS_REGION }}
                  deployment_package: deploy.zip
                  wait_for_environment_recovery: 1800

            # [ON SUCCESS] Update Deployment Status = Success
            - name: Update deployment status (success)
              if: success()
              uses: chrnorm/deployment-status@v2
              with:
                  token: "${{ github.token }}"
                  environment-url:
                      ${{ steps.deployment.outputs.environment_url }}
                  deployment-id: ${{ steps.deployment.outputs.deployment_id }}
                  state: "success"

            # [ON ERROR] Update deployment status = Failure
            - name: Update deployment status (failure)
              if: failure()
              uses: chrnorm/deployment-status@v2
              with:
                  token: "${{ github.token }}"
                  environment-url:
                      ${{ steps.deployment.outputs.environment_url }}
                  deployment-id: ${{ steps.deployment.outputs.deployment_id }}
                  state: "failure"
